name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.1
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Type Check
        run: bun run typecheck
      - name: Lint Check
        run: bun run lint
      - name: Format Check
        run: bun run format
      - name: Run Tests
        run: bun run test
      - name: Build Check
        run: bun run build
